# Generated by Django 5.0.1 on 2024-01-22 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_task_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='place_of_service',
            field=models.CharField(choices=[('remote', 'Can be done remotely'), ('on_site', 'Required to be present at the address')], max_length=20, null=True),
        ),
    ]
