# Generated by Django 5.0 on 2024-01-23 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_alter_task_place_of_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='place_of_service',
            field=models.CharField(choices=[('remote', 'Can be done remotely'), ('on_site', 'Required to be present at the address')], default='on_site', max_length=20),
        ),
    ]
