# Generated by Django 5.0.1 on 2024-01-23 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0006_task_photos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='photos',
        ),
    ]
