# Generated by Django 5.0.1 on 2024-01-23 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0007_remove_task_photos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='place_of_service',
            field=models.CharField(choices=[('remote', 'Можно выполнить удалённо'), ('on_site', 'Нужно присутствие по адресу')], default='on_site', max_length=20),
        ),
    ]
